[package]
name = "day20-rust"
version = "0.1.0"
authors = ["wangy <yingge_gzb@qq.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
lazy_static = "1.4.0"
ndarray = "0.14.0"
peg = "0.6.3"
